### ISSUE TITLE
core log: many entries in the core log 

### ISSUE THREAD

**Issue by dutch-kay** [elad-bar/ha-dahuavto#4]
hi,
I installed your Dahua VTO integration. Now I get loads of entries from the module:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2020-12-08 17:17:23 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dahuavto doing I/O at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth)
2020-12-08 17:17:23 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dahuavto doing I/O at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth)
2020-12-08 17:17:28 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dahuavto doing I/O at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth)
2020-12-08 17:17:28 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dahuavto doing I/O at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth)

Can you help me?

greetings 
Kay

**Comment by ALERTua** [comment]
i have the same issue

**Comment by kamilian2** [comment]
Logger: custom_components.dahuavto.dahuavto_data
Source: custom_components/dahuavto/dahuavto_data.py:112
Integration: Dahua VTO Integration (documentation)
First occurred: 16:27:11 (91 occurrences)
Last logged: 16:34:38

VTO Request to /cgi-bin/magicBox.cgi?action=getSystemInfo failed, Error: 404 Client Error: Not Found for url: http://192.168.1.110:80/cgi-bin/magicBox.cgi?action=getSystemInfo, Line: 101
VTO Request to /cgi-bin/recordFinder.cgi?action=find&name=VideoTalkLog failed, Error: 404 Client Error: Not Found for url: http://192.168.1.110:80/cgi-bin/recordFinder.cgi?action=find&name=VideoTalkLog, Line: 101
